# Generated by Django 2.0.5 on 2018-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='owner',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.IntegerField(default='', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='person',
            name='major',
            field=models.CharField(default='', max_length=50, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_id',
            field=models.IntegerField(default='', verbose_name='学号'),
        ),
    ]
