# Generated by Django 2.0.5 on 2018-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_person_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password2',
            field=models.CharField(default='', max_length=50, verbose_name='密码2'),
        ),
    ]
