# Generated by Django 2.0.5 on 2018-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_person_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password2',
        ),
    ]
