# Generated by Django 2.0.5 on 2018-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_person_password2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='cul_name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='brief_intro',
            field=models.TextField(blank=True, default='', verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='teacher_name',
            field=models.CharField(default='', max_length=20, verbose_name='任课教师'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_id',
            field=models.IntegerField(default=0, verbose_name='学号'),
        ),
        migrations.AlterModelTable(
            name='curriculum',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
