# Generated by Django 2.0.5 on 2018-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180614_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='姓名'),
        ),
    ]
