# Generated by Django 2.0.5 on 2018-07-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180624_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
