# Generated by Django 2.0.5 on 2018-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='content',
            field=models.FileField(upload_to='upload/data/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='filename',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
    ]
