# Generated by Django 2.0.5 on 2018-05-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['text'], 'verbose_name': '功能', 'verbose_name_plural': '功能'},
        ),
        migrations.AddField(
            model_name='column',
            name='function',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.Function', verbose_name='所属功能'),
        ),
    ]
