# Generated by Django 2.0.5 on 2018-05-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180529_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论'},
        ),
        migrations.AlterModelOptions(
            name='thumbup',
            options={'verbose_name': '点赞'},
        ),
    ]
