# Generated by Django 2.0.5 on 2018-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180529_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
