# Generated by Django 2.0.5 on 2018-06-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180529_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name'], 'verbose_name_plural': '栏目'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['text'], 'verbose_name_plural': '功能'},
        ),
    ]
