# Generated by Django 2.0.5 on 2018-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
