# Generated by Django 2.0.5 on 2018-07-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20180710_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='楼层'),
        ),
    ]
